### ISSUE TITLE
Incorrectly required fields in gc_update_channel_by_url

### ISSUE THREAD

**Issue by pmdevita** [sendbird/sendbird-platform-sdk-python#9]
According to the [Platform API Docs](https://sendbird.com/docs/chat/platform-api/v3/channel/managing-a-channel/update-a-group-channel#2-request-body), all parameters passed into the body of Update a Group Channel are optional. However, for the Python library, they are all marked as required [docs](https://github.com/sendbird/sendbird-platform-sdk-python/blob/main/docs/GroupChannelApi.md#gc_update_channel_by_url) [model](https://github.com/sendbird/sendbird-platform-sdk-python/blob/0e2760286d5e2b3c5ea5ed7b78a925cec02e5895/sendbird_platform_sdk/model/gc_update_channel_by_url_data.py#L122). This should be updated to reflect their optional status in the Platform API.

**Comment by jerry-jeon-sb** [comment]
@pmdevita Thanks for reporting this. It's been fixed in 1.0.24. 
But it might take time to release this to pypi. Let me ping you if we released it in pypi

**Comment by pmdevita** [comment]
Sorry for only getting back to this now but I just realized this was not fixed in 1.0.24. The data model for the request still requires all of the parameters https://github.com/sendbird/sendbird-platform-sdk-python/blob/main/sendbird_platform_sdk/model/gc_update_channel_by_url_data.py

**Comment by jerry-jeon** [comment]
@pmdevita sorry, I was confused with Open Channel. I fixed it in 1.0.26, could you check this again?

**Comment by akshayraj3000** [comment]
@jerry-jeon the model still appears to require all parameters for me. The updated docs reference an update_a_group_channel method and model, but I don't think this is available in the latest sdk version.
